spring.application.name=capstone

spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.initialize-schema=true
spring.ai.vectorstore.chroma.collection-name=capstone

spring.ai.model.embedding=google-genai

spring.ai.google.genai.api-key=AIzaSyBTHQ2oN1gg5g6mSSgGn6CWk5FR-6nO4BM
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.google.genai.embedding.api-key=AIzaSyBzm4fGudULbf2E0PXztwoh4F8fmP7buTg

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.init.chat.include=true
spring.ai.ollama.chat.options.keep-alive=1h
spring.ai.ollama.chat.options.num-predict=300
spring.ai.ollama.chat.options.num-ctx=4096
spring.ai.ollama.chat.options.temperature=0.3



finnhub.api.key=d74l0opr01qg1eo5sikgd74l0opr01qg1eo5sil0
project.chat.model=ollama
project.chat.threshold=0.5

